### ISSUE TITLE
Combination of 'cenbii-procid-ubl::peppol-transport-as4-v2_0' and transport profile(s) not found.

### ISSUE THREAD

**Issue by perneninag** [OxalisCommunity/oxalis-ng#1]
I have compiled new oxalis-ng source code and trying to run standalone client to send message to testbed but getting below error.

Message failed : Combination of 'cenbii-procid-ubl::peppol-transport-as4-v2_0' and transport profile(s) not found.

2024-12-11 04:02:27,525 ERROR [network.oxalis.ng.Main] Execution failed: network.oxalis.ng.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: network.oxalis.ng.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at network.oxalis.ng.Main.main(Main.java:228)
Caused by: network.oxalis.ng.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.ng.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:106)
        at network.oxalis.ng.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:96)
        at network.oxalis.ng.TransmissionTask.performTransmission(TransmissionTask.java:157)
        at network.oxalis.ng.TransmissionTask.call(TransmissionTask.java:90)
        at network.oxalis.ng.TransmissionTask.call(TransmissionTask.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Total time spent: 1s
Attempted to send 0 files
Failed transmissions: 1

**Comment by perneninag** [comment]
oxalis.conf file :
oxalis.pmode.file="pmode.xml"

oxalis.module.as4.common = {
    class = network.oxalis.ng.as4.common.As4CommonModule
}

oxalis.module.as4.inbound = {
    class = network.oxalis.ng.as4.inbound.As4InboundModule
    dependency = inbound.servlet
}

oxalis.module.as4.outbound = {
    class = network.oxalis.ng.as4.outbound.As4OutboundModule
    dependency = outbound.lookup
}
transport.as4_peppol_v2 = {
    profile: peppol-transport-as4-v2_0
    sender: oxalis-as4
    weight: 9001
}

pmode.xml: 
   <BusinessInfo>
        <Service>
            <Value>urn:www.cenbii.eu:profile:bii01:ver2.0</Value>
            <Type>cenbii-procid-ubl</Type>
        </Service>
        <Action>busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice</Action>
    </BusinessInfo>
    <Protocol>
        <Address>https://peppol.anusaar.com/as4</Address>
        <TransportProfile>peppol-transport-as4-v2_0</TransportProfile>
    </Protocol>
